export const degreeData =[
{"degree":"Sales"},
{"degree":"Research and Development"},
{"degree":"Marketing"},
{"degree":"Support"},
{"degree":"Research and Development"},
{"degree":"Sales"},
{"degree":"Business Development"},
{"degree":"Engineering"},
{"degree":"Accounting"},
{"degree":"Human Resources"},
{"degree":"Product Management"},
{"degree":"Engineering"},
{"degree":"Services"},
{"degree":"Accounting"},
{"degree":"Legal"},
{"degree":"Accounting"},
{"degree":"Training"},
{"degree":"Business Development"},
{"degree":"Training"},
{"degree":"Research and Development"},
{"degree":"Legal"},
{"degree":"Training"},
{"degree":"Business Development"},
{"degree":"Business Development"},
{"degree":"Services"},
{"degree":"Support"},
{"degree":"Human Resources"},
{"degree":"Business Development"},
{"degree":"Business Development"},
{"degree":"Training"},
{"degree":"Human Resources"},
{"degree":"Product Management"},
{"degree":"Marketing"},
{"degree":"Training"},
{"degree":"Support"},
{"degree":"Human Resources"},
{"degree":"Legal"},
{"degree":"Sales"},
{"degree":"Human Resources"},
{"degree":"Training"},
{"degree":"Business Development"},
{"degree":"Business Development"},
{"degree":"Accounting"},
{"degree":"Human Resources"},
{"degree":"Sales"},
{"degree":"Services"},
{"degree":"Accounting"},
{"degree":"Engineering"},
{"degree":"Business Development"},
{"degree":"Sales"},
{"degree":"Legal"},
{"degree":"Human Resources"},
{"degree":"Business Development"},
{"degree":"Marketing"},
{"degree":"Product Management"},
{"degree":"Research and Development"},
{"degree":"Marketing"},
{"degree":"Marketing"},
{"degree":"Human Resources"},
{"degree":"Services"},
{"degree":"Marketing"},
{"degree":"Human Resources"},
{"degree":"Business Development"},
{"degree":"Engineering"},
{"degree":"Business Development"},
{"degree":"Business Development"},
{"degree":"Business Development"},
{"degree":"Sales"},
{"degree":"Marketing"},
{"degree":"Accounting"},
{"degree":"Accounting"},
{"degree":"Services"},
{"degree":"Sales"},
{"degree":"Business Development"},
{"degree":"Training"},
{"degree":"Engineering"},
{"degree":"Engineering"},
{"degree":"Research and Development"},
{"degree":"Marketing"},
{"degree":"Human Resources"},
{"degree":"Engineering"},
{"degree":"Engineering"},
{"degree":"Legal"},
{"degree":"Legal"},
{"degree":"Product Management"},
{"degree":"Engineering"},
{"degree":"Marketing"},
{"degree":"Business Development"},
{"degree":"Research and Development"},
{"degree":"Sales"},
{"degree":"Accounting"},
{"degree":"Legal"},
{"degree":"Product Management"},
{"degree":"Human Resources"},
{"degree":"Marketing"},
{"degree":"Training"},
{"degree":"Marketing"},
{"degree":"Sales"},
{"degree":"Sales"},
{"degree":"Training"}]