export const locationData =[{"location":"Dầu Tiếng"},
{"location":"Nicolet"},
{"location":"Tadrart"},
{"location":"Aglipay"},
{"location":"Mâcon"},
{"location":"Cigalontang"},
{"location":"Divinópolis"},
{"location":"Bom Jesus da Lapa"},
{"location":"Santa Tecla"},
{"location":"Aurora"},
{"location":"Pajarillo"},
{"location":"Dalongtan"},
{"location":"Āsbe Teferī"},
{"location":"Parada de Todeia"},
{"location":"Namwala"},
{"location":"Wola Sernicka"},
{"location":"Haparanda"},
{"location":"Jiaqu"},
{"location":"Mashan"},
{"location":"Gunungjulang"},
{"location":"Banjar Bengkelgede"},
{"location":"Cikiray"},
{"location":"Siaya"},
{"location":"Dolní Čermná"},
{"location":"San Felipe"},
{"location":"Ganggawang"},
{"location":"Fanrong"},
{"location":"Fenghuang"},
{"location":"Gesing"},
{"location":"Hamburg Harvestehude"},
{"location":"San Miguel Chicaj"},
{"location":"Saint-Avertin"},
{"location":"Sydney"},
{"location":"Kamo"},
{"location":"Sanxi"},
{"location":"Čoka"},
{"location":"Novais"},
{"location":"Köyliö"},
{"location":"Ugra"},
{"location":"Santo Rosario"},
{"location":"Entre Rios"},
{"location":"Marseille"},
{"location":"Okaya"},
{"location":"San Mateo"},
{"location":"Baolong"},
{"location":"Kademangan"},
{"location":"Wydminy"},
{"location":"Bachok"},
{"location":"Waterbury"},
{"location":"Łęknica"},
{"location":"Pasirtundun"},
{"location":"Tromsø"},
{"location":"Mbouda"},
{"location":"Wielki Kack"},
{"location":"Makīnsk"},
{"location":"Oropesa"},
{"location":"Trompsburg"},
{"location":"Yanqi"},
{"location":"Fatumuti"},
{"location":"Rossosh’"},
{"location":"Kuanghe"},
{"location":"Kutamangu"},
{"location":"Kumlinge"},
{"location":"Seoul"},
{"location":"Örebro"},
{"location":"Eshan"},
{"location":"Chaviña"},
{"location":"Huaqiao"},
{"location":"Qalyūb"},
{"location":"Biguaçu"},
{"location":"Fatikchari"},
{"location":"Vónitsa"},
{"location":"Lukhovka"},
{"location":"La Plaine-Saint-Denis"},
{"location":"Shuangbaiyang"},
{"location":"Ciénega"},
{"location":"Awjilah"},
{"location":"Amparafaravola"},
{"location":"Palestina"},
{"location":"Kyperoúnta"},
{"location":"Oklahoma City"},
{"location":"San Francisco"},
{"location":"El Paso"},
{"location":"Aija"},
{"location":"Riba de Ave"},
{"location":"Sanzao"},
{"location":"Granja"},
{"location":"Budapest"},
{"location":"Protvino"},
{"location":"Raszczyce"},
{"location":"Sanying"},
{"location":"Tempeh Tengah"},
{"location":"Rymanów"},
{"location":"Temandangjero"},
{"location":"Kaduna"},
{"location":"Smimou"},
{"location":"Gudurica"},
{"location":"Yanjiao"},
{"location":"Sukaraja"},
{"location":"Shenzhong"}]