export const missionariesData =[
    {"lesson":3,"description":"recieved a priesthood blessing from a friend and now [SubjectPronoun] wants to learn more"},
    {"lesson":2,"description":"wants to grow closer to God and find purpose in life"},
    {"lesson":"wow","description":"often worries that God is disappointed in [ObjectPronoun] for not following him better and wants to know how to change"},
    {"lesson":0,"description":"met [PossessivePronoun] [Partner] the beginning of her sophomore year and they fell in love. They are happily living together until they finish college and then plan to move to California together. [Name] has been meeting with the missionaries for a few weeks because [SubjectPronoun] was doing research on religion in the area for a journalism class and came across the church website where [SubjectPronoun] requested a book of mormon. The missionaries brought it to [ObjectPronoun] door and invited [ObjectPronoun] to learn more. [SubjectPronoun] is really liking what [SubjectPronoun] is learning and has been to church once in the YSA ward. [SubjectPronoun] has also made some friends there. [PossessivePronoun] [Partner] is supportive but not interested. You have taught [ObjectPronoun] lessons 1-3 and [SubjectPronoun] liked them and wants to keep learning. [SubjectPronoun] also loves to read the book of mormon and tells you that [SubjectPronoun] feels that it's true"},
    {"lesson":3,"description":"is married, and both [SubjectPronoun] and [PossessivePronoun] [Spouse] are social drinkers. One of [Name]'s favorite ways to relax is to watch football with a six pack of beer. You have already taught both [Name] and [PossessivePronoun] the first 3 lessons, and they have been to church 2 times with their kids"},
    {"lesson":2,"description":"wants to learn more about what makes the Church of Jesus Christ of Latter-day Saints different from other Christian churches"},
    {"lesson":"wow","description":"hopes that the missionaries can help [ObjectPronoun] grow a relationship with God"},
    {"lesson":"loc","description":"struggles to understand why bad things happen to good people"},
    {"lesson":3,"description":"is looking to develop a more personal relationship with God"},
    {"lesson":1,"description":"likes reading the Bible and talking about it"},
    {"lesson":2,"description":"was recently diagnosed with cancer. When [SubjectPronoun] find out about the cancer, [SubjectPronoun] went to [PossessivePronoun] for help. The pastor told [ObjectPronoun] that it was a result of God being displeased with [ObjectPronoun]. Fortunately, [Name] will likely recover from the cancer, but this experience caused [ObjectPronoun] to visit several other churches of different faiths, but none of them have felt right yet"},
    {"lesson":3,"description":"wants to know if God really does exist and how that affects [ObjectPronoun]"},
    {"lesson":2,"description":"is trying to find [PossessivePronoun] purpose in life outside of track and field and school"},
    {"lesson":1,"description":"has been taught the first two lessons so far, and accepted everything in those lessons. [SubjectPronoun] felt good about the Book of Mormon when [SubjectPronoun] prayed about it"},
    {"lesson":2,"description":"has been taught the first 3 lessons so far and is excited about [PossessivePronoun] baptism coming up next month. [SubjectPronoun] does not drink or smoke, but drinks coffee every morning"},
    {"lesson":"loc","description":"has been taught the first 3 lessons so far and is excited about [PossessivePronoun] baptism coming up next month. [SubjectPronoun] does not drink or smoke, but drinks coffee every morning"},
    {"lesson":3,"description":"has been questioning whether God exists and would like a fresh perspective"},
  
]