export const occupationData = [
{"occupation":"Quality Control Specialist"},
{"occupation":"Senior Sales Associate"},
{"occupation":"Environmental Specialist"},
{"occupation":"Office Assistant I"},
{"occupation":"Graphic Designer"},
{"occupation":"Editor"},
{"occupation":"Research Associate"},
{"occupation":"Food Chemist"},
{"occupation":"Internal Auditor"},
{"occupation":"Senior Cost Accountant"},
{"occupation":"Cost Accountant"},
{"occupation":"Research Nurse"},
{"occupation":"Administrative Officer"},
{"occupation":"Marketing Manager"},
{"occupation":"Senior Quality Engineer"},
{"occupation":"Technical Writer"},
{"occupation":"Internal Auditor"},
{"occupation":"Computer Systems Analyst III"},
{"occupation":"Administrative Assistant I"},
{"occupation":"Human Resources Manager"},
{"occupation":"Structural Engineer"},
{"occupation":"Tax Accountant"},
{"occupation":"Safety Technician III"},
{"occupation":"Accounting Assistant III"},
{"occupation":"Research Nurse"},
{"occupation":"Electrical Engineer"},
{"occupation":"VP Sales"},
{"occupation":"Senior Quality Engineer"},
{"occupation":"Financial Analyst"},
{"occupation":"Analyst Programmer"},
{"occupation":"Community Outreach Specialist"},
{"occupation":"Assistant Media Planner"},
{"occupation":"Social Worker"},
{"occupation":"Registered Nurse"},
{"occupation":"Account Executive"},
{"occupation":"Librarian"},
{"occupation":"Research Associate"},
{"occupation":"Paralegal"},
{"occupation":"Internal Auditor"},
{"occupation":"Software Consultant"},
{"occupation":"Librarian"},
{"occupation":"Professor"},
{"occupation":"Librarian"},
{"occupation":"Community Outreach Specialist"},
{"occupation":"Senior Cost Accountant"},
{"occupation":"Chemical Engineer"},
{"occupation":"Senior Developer"},
{"occupation":"Geological Engineer"},
{"occupation":"Sales Associate"},
{"occupation":"Graphic Designer"}]