export const schoolData =[
{"school":"Arab Open University"},
{"school":"University of Twente"},
{"school":"Dakota State University"},
{"school":"Dhaka University of Engineering and Technology"},
{"school":"National Academy for Theatre and Film Arts \"Krustju Sarafov\""},
{"school":"Westbrook University "},
{"school":"Perm State University"},
{"school":"Maxim Gorky Institute of Literature"},
{"school":"Luther College"},
{"school":"Maryam Institute of Higher Education"},
{"school":"Castleton State College"},
{"school":"Water Resources University"},
{"school":"Green University of Bangladesh"},
{"school":"Chongqing Medical University"},
{"school":"University of Halifax, Birmingham Campus"},
{"school":"University of Pavia"},
{"school":"Aston University"},
{"school":"Tajikistan International University"},
{"school":"Universiti Malaysia Sabah"},
{"school":"Fuji Women's College"},
{"school":"Japanese Red Cross College of Nursing"},
{"school":"Aksum University"},
{"school":"Ecole Nationale Supérieur des Ingénieur des Etudes et Techniques d'Armement"},
{"school":"Aventis School of Management"},
{"school":"Northwood University, Texas Campus"},
{"school":"Intercollege"},
{"school":"Middle East Technical University"},
{"school":"Omsk State Agrarian University"},
{"school":"Los Angeles College of Chiropractic"},
{"school":"Miyagi University of Education"},
{"school":"Universidade de Coimbra"},
{"school":"National Chi Nan University"},
{"school":"Conway School of Landscape Design"},
{"school":"Bethany College West Virginia"},
{"school":"Universidad España de Durango"},
{"school":"University of Virginia"},
{"school":"University of Melbourne"},
{"school":"University of Colorado at Boulder"},
{"school":"Presbyterian University College"},
{"school":"Ural State Academy of Law"},
{"school":"University of Northern Philippines"},
{"school":"Universidad Católica Anselmo Llorente"},
{"school":"Universidad del Centro Educativo Latinoamericano Rosario"},
{"school":"University of Arkansas at Pine Bluff"},
{"school":"Universidad de Santiago de Compostela"},
{"school":"Université de Limoges"},
{"school":"Nagoya College of Music"},
{"school":"Universidad de Valladolid"},
{"school":"Persian Gulf University"},
{"school":"Kansas City Art Institute"},
{"school":"Abubakar Tafawa Balewa University"},
{"school":"Vermont Technical College"},
{"school":"Lakeview College of Nursing"},
{"school":"Northern Jiaotong University"},
{"school":"Universidad Internacional Menéndez Pelayo"},
{"school":"Mahamakut Buddhist University"},
{"school":"Osaka Dental University"},
{"school":"Universidad de Aquino Bolivia"},
{"school":"Silesian Academy of Medicine in Katowice"},
{"school":"University of Liberal Arts"},
{"school":"Ibaraki University"},
{"school":"Institut National des Sciences Appliquées de Rouen"},
{"school":"Gannon University"},
{"school":"Institute of Business Administration (IBA)"},
{"school":"Chiba University"},
{"school":"Bells University of Technology"},
{"school":"University of Michigan - Ann Arbor"},
{"school":"Université de Liège"},
{"school":"Shandong Medical University"},
{"school":"Universidad Obrera de Mexico"},
{"school":"Texas A&M University - Corpus Christi"},
{"school":"University College of Cape Breton"},
{"school":"Universidad Nacional de Chimborazo"},
{"school":"Shibaura Institute of Technology"},
{"school":"Universidad Nacional de Catamarca"},
{"school":"Prague College"},
{"school":"Azzahra University"},
{"school":"Concordia College, Selma"},
{"school":"Free International University of Moldova"},
{"school":"Instituto Politécnico do Cávado e do Ave"},
{"school":"School of Pharmacy, University of London"},
{"school":"Aventis School of Management"},
{"school":"Nanjing University of Traditional Chinese Medicine"},
{"school":"University of Naples Federico II"},
{"school":"Ecole Supérieure de Commerce de Dijon"},
{"school":"Universidad Nacional Jorge Basadre Grohmann"},
{"school":"Universidade do Estado do Rio de Janeiro"},
{"school":"Kumasi Polytechnic "},
{"school":"Fachhochschule für Verwaltung und Rechtspflege Berlin"},
{"school":"University of Wisconsin - Eau Claire"},
{"school":"Shanghai Second Medical University"},
{"school":"Targu-Mures University of Theatre"},
{"school":"Marian College"},
{"school":"Technische Universität Dresden"},
{"school":"Brunel University Uxbridge"},
{"school":"British College of Osteopathic Medicine"},
{"school":"Jaipur National University"},
{"school":"Imperial College London"},
{"school":"Université de Montpellier II"},
{"school":"Northwestern University of the Philippines"}]